name: bobtiki.me
favicon: null
layout_spectrum: 1
typography_spectrum: 0.16254502348601818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#2b181a'
    - '#80526f'
    - '#4a4273'
    - '#fffefb'
  brandStrength: 0.625
  lightness: 0.2861353976186365
  saturation: 0.125
  rhythmicContrast: 0.6170314748305827
purpose: []
