name: bobtiki.me
favicon: null
layout_spectrum: 0.00928
typography_spectrum: 0.65003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#130f0e'
    - '#fffffb'
    - '#767064'
    - '#aaa297'
    - '#704a31'
  brandStrength: 0.625
  lightness: 0.2861353976186365
  saturation: 0.125
  rhythmicContrast: 0.6170314748305827
purpose: []
