name: bobtiki.me
favicon: null
layout_spectrum: 0.23833210580050945
typography_spectrum: 0.16254502348601818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6008530729450285
  lightness: 0.2861353976186365
  saturation: 0.13991565583273768
  rhythmicContrast: 0.6170314748305827
purpose: []
